services:
  db:
    image: mysql:8.4.5
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: rest_api_springboot_estudo
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - rlourenco-network
  rest-with-spring-boot-rlourenco:
    image: lourenc0ricardo/rest-with-spring-boot
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_api_springboot_estudo?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1234
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - rlourenco-network
networks:
  rlourenco-network:
    driver: bridge
