cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  application:
    name: rest-api-with-springboot-2025
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-api-springboot-estudo?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: INFO
    # root: WARN
    # br.com.rlourenco1998: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true